### ISSUE TITLE
tech stacks of this project

### ISSUE THREAD

**Issue by thoughtlessmind** [KalleHallden/BookOmatic#19]
Which tech stacks and frameworks are you planning to use for this project?

**Comment by jonm24** [comment]
^bump

**Comment by thoughtlessmind** [comment]
Interesting... But what does that mean?😅

**Comment by jonm24** [comment]
hahahaha i just wanted to ask the same question/get your question answered

**Comment by thoughtlessmind** [comment]
Ohh! 
I'm also waiting for the answer.

**Comment by KalleHallden** [comment]
Hi!

So my plan based on the poll I did here: https://www.youtube.com/post/Ugy7MjdpXAE2wroWEYN4AaABCQ

is to use Django and Python for building out the site. And then firebase for whatever backend stuff might be needed :)

I will add this to the readme, I just need to look into how to add it to the readme proeperly or where this type of information is usually kept in open source projects. If anyone is swift with this stuff and knows exactly where to put it, feel free to do it and create a pull request ;)

**Comment by thoughtlessmind** [comment]
okay...
Awesome.
