### ISSUE TITLE
[Documentation] Add a "CONTRIBUTING" file

### ISSUE THREAD

**Issue by AlbertCoolGuy** [KalleHallden/BookOmatic#23]
Add a "CONTRIBUTING" file that explains how to contribute to the project.

**Comment by BenjaminCCross** [comment]
What should be in this contributing document? One big thing I can think of is this.
- When making a pull request, reference a specific issue. If there is no specific issue then make one. This will allows to keep track of issues as well as see growth and change.

**Comment by AlbertCoolGuy** [comment]
That sounds good but I also thought like guidelines for making a pull
request.

**Comment by BenjaminCCross** [comment]
Here are some useful tips: [link](https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests).
More specific ideas:
- When making a pull request include the number of the issue in the title.
- Use clear and succinct commit messages. Useful but long guide: [link](https://chris.beams.io/posts/git-commit/)
- Keep your pull request to one issue. Smaller is better.
- When describing the bull request don't assume past history with the issue.
- If you need help please include areas of concern to help reviewers know what they can do.
- add screen shots if you are including visual changes
- @mention devs that you specifically want to see the PR and mention why. Such as having experience with the issue.

Suggestions? Also ideas on other forms of contribution ie documentation, issue gardening etc.?

**Comment by AlbertCoolGuy** [comment]
Could you make a pull request with a contributing file?

**Comment by BenjaminCCross** [comment]
Yeah absolutely. Though now I am concerned it won't be up to par...

**Comment by BenjaminCCross** [comment]
@AlbertCoolGuy @KalleHallden this issue can be closed after the merge. I can't close it for some reason, but as admin or the person who opened it one of you can.
