### ISSUE TITLE
Add labels to issues/pull requests

### ISSUE THREAD

**Issue by AlbertCoolGuy** [KalleHallden/BookOmatic#30]
If someone wants to solve a issue it would be easier for them to find a issue they could fix.

**Comment by offxcial-erik** [comment]
Kalle has already stated that in the HowToContribute file.

**Comment by AlbertCoolGuy** [comment]
Oh yeah, I just saw that. And actually the HowToContribute file is not made
by Kalle.

**Comment by erik-gross-hardt** [comment]
Sorry you are totally right! Corrected comment:
> @BenjaminCCross has already stated that in the HowToContribute file.
