### ISSUE TITLE
Where has all code gone??

### ISSUE THREAD

**Issue by sk1122** [KalleHallden/BookOmatic#35]
![Screenshot_2020-03-21-02-54-13-609_com android chrome](https://user-images.githubusercontent.com/40713709/77207431-586e4000-6b1f-11ea-814b-5aea321de26d.png)

**Comment by saibottob** [comment]
Up to this moment no code has been generated.

**Comment by AlbertCoolGuy** [comment]
Please close this issue because it's not relevant.

**Comment by Yuvateja01** [comment]
New  here  so just asking no starter code generated (no pull requests merged)??

**Comment by AlbertCoolGuy** [comment]
Some pull requests have been merged, but only documentation files. Someone
made a Django initial setup but I think Kalle should do it.
