### ISSUE TITLE
Firebase?

### ISSUE THREAD

**Issue by brianraila** [KalleHallden/BookOmatic#36]
I am against the idea of using Firebase as the datastore because the source is proprietary and therefore it will be hard to promise consistent feature-set or consistent API scope. APIs usually change. The databases change. 
I suggest using a natively supported database by Django ORM. Postgres 😊
As I am aware, Firestore is still on beta.

**Comment by brianraila** [comment]
This also opens up the ability of 100% self hosting the app.

**Comment by 0x7081** [comment]
+1 on this Issue.
I think it would be better to use a Django supported database, because I don't see any need for something like Firebase.
Also you have an easy way to containerize the whole application and host it yourself or in a company maybe, behind bad corporate proxies.

**Comment by brianraila** [comment]
@KalleHallden Give your suggestions on this. As it will influence a whole lot of how the project will go on.

**Comment by ercadev** [comment]
I agree on this. I also think it could have been good if the stack was splited. As it is now its only python which leave out many people who is working in other languages. Kalle has 175k subscribers on youtube. maybe 30% is python 30% javascript and 30% other. Lets split it up so as many of the people can join.

**Example:**
Database: MySQL
Backend: Python
Frontend Website: Vuejs or React
Mobile: Flutter

This would probably make 90% of the subscribers able to join instead of 30%.

**Comment by osamamhd** [comment]
I also on this, firebase is unavailable in my area, so prefer to use other.

**Comment by shohamc1** [comment]
Additionally I believe there is no good Firebase ORM, so it might be **easier** to use PostgreSQL/MySQL.

**Comment by iamharpar** [comment]
Ya

**Comment by sourcificer** [comment]
> I agree on this. I also think it could have been good if the stack was splited. As it is now its only python which leave out many people who is working in other languages. Kalle has 175k subscribers on youtube. maybe 30% is python 30% javascript and 30% other. Lets split it up so as many of the people can join.
> 
> **Example:**
> Database: MySQL
> Backend: Python
> Frontend Website: Vuejs or React
> Mobile: Flutter
> 
> This would probably make 90% of the subscribers able to join instead of 30%.

I agree
How about using [gatsbyjs](https://www.gatsbyjs.org/) it's build on top of react and it has a native PWA generator eliminating the need to create a separate mobile application

Besides BookOmatic doesn't require many permissions (virtually none) therefore a PWA will work just fine

Making the stack: 

- Database: MySQL

- Backend: Python
- Frontend Website & mobile (PWA): gatsbyjs

**Comment by alucardthefish** [comment]
I agree with this issue topic. I like the idea of using PostgreSQL as Database.

**Comment by l3str4nge** [comment]
I think PostgreSQL will be the best idea.
