### ISSUE TITLE
Initial Django Setup

### ISSUE THREAD

**Issue by 0x7081** [KalleHallden/BookOmatic#38]
Hi there,

I think @KalleHallden should do an initial Django setup, so we have the main project structure to start coding too.

It would be better if the main author creates the initial setup, so he has the ability to name the things like he wants to. Also it would be great to do this before anyone starts coding, so we don't have a huge mess later on to merge all the different projects into one.

**Comment by BrianRuizy** [comment]
I've made a pull request with initial boilerplate for the Django app. 
See here: #37 .

**Comment by 0x7081** [comment]
I saw your pull request, but as I said I think it's better if Kalle creates the initial app.

**Comment by Kieran7741** [comment]
Was Flask considered ? For a project that isn't massive I think Flask is a better choice. Or instead of using firebase we could use Flask to build out our own services which can then put into Docker containers.

**Comment by BrianRuizy** [comment]
@Kieran7741 The stack was decided via a YouTube poll system, I believe. Yes, Flask may have been a viable alternative. However, Django provides more out-the-box to generate a working product in less time.

**Comment by 0x7081** [comment]
Since there is a initial Django setup now, I close this issue.
