### ISSUE TITLE
Progressive WebApp.

### ISSUE THREAD

**Issue by erik-gross-hardt** [KalleHallden/BookOmatic#42]

**Comment by offxcial-erik** [comment]
How can I label this issue. I am not that experienced with GitHub 🙃.

**Comment by szimeth-jozef** [comment]
I think it should be labelled as question. :thumbsup:

**Comment by pixlmint** [comment]
You can also have much more simple web apps (those that have a small banner at the bottom in Chrome Mobile that prompt to pin the site to the homescreen). This can be achieved very easily, there just needs to be a manifest, and there can be some JavaScript that stores stuff in the phone's memory. So this can easily be done with Django

**Comment by offxcial-erik** [comment]
@ChristianGroeber That's exactly what I am talking about. Those are called PWAs and they were / are developed by Google.

**Comment by KalleHallden** [comment]
Yes I think that this is a perfect idea! :)
