### ISSUE TITLE
Creation of Django Apps

### ISSUE THREAD

**Issue by jeremychrimes** [KalleHallden/BookOmatic#45]
I think that it would be a good idea to create Django Applications which divide up the application into seperate components or more specifically Django Apps. 
## Proposed Apps
+ User Preferences 
A place for the user preferences to be stored such as prefered calendars, profile information, 
+ Calendar
Displays a calendar for scheduling events. 
+ Event Booking
Handles the creation of events and scheduling. 
+ Calendar Service 
Handles accesing of calendars (could potentially be split up into a different service for each calendar provider such as google, icloud etc)
I will create a pull request with the creation of these apps. If someone could just critique this plan that would be great.

**Comment by l3str4nge** [comment]
How about Accounts app with all necessary functions like:

- register, login, logout, password reset
- social media sign in (Gmail, Facebook, Twitter etc.)
- templates/static for above functionality

**Comment by jeremychrimes** [comment]
@mateuszz0000  Generally convention with Django is to use the settings app to handle authentication as this is Global and accessible to all components of the application without the need to mass import.
