### ISSUE TITLE
Slack/IRC/Something else?

### ISSUE THREAD

**Issue by l3str4nge** [KalleHallden/BookOmatic#69]
Hello!
I have not seen such a topic so I create a new one.
I propose to create a channel where we could discuss the project. My proposition is Slack but I really don't care. If such a channel already exists, please let me know :)

**Comment by dansholds** [comment]
Agreed, i'm keen to get stuck into this project and it would be good to have a slack to the 'team' can talk more direct

**Comment by mralexcraven3** [comment]
I think Slack or Discord

**Comment by rutansh** [comment]
Agree

**Comment by l3str4nge** [comment]
How about https://gitter.im/ ?

**Comment by BrianRuizy** [comment]
[![Gitter](https://badges.gitter.im/BookOmatic/community.svg)](https://gitter.im/BookOmatic/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
Gitter is lightweight but also allows us to make rooms, for specific discussions.

This issue can be closed now, @mateuszz0000. 
See #86 

--
@danielholdsworth, @rutansh, @mralexcraven3

**Comment by l3str4nge** [comment]
Thanks!
