### ISSUE TITLE
django error - page not found at /

### ISSUE THREAD

**Issue by JBetts97** [KalleHallden/BookOmatic#83]
I have followed the steps to build and run the development server.

When I run the server, I get no errors, but when I try to open (127.0.0.1:8000) I receive following error message in python console:
![image](https://user-images.githubusercontent.com/38386086/80966316-351bfd80-8e0c-11ea-9a4d-863d2f7d8311.png)

When I look at the frontend I get a similar error:
![image](https://user-images.githubusercontent.com/38386086/80966367-50870880-8e0c-11ea-8226-034a07da2395.png)

I am using Python3 on MacOS. Any help is greatly appreciated.

Kindest Regards,
Joseph

**Comment by l3str4nge** [comment]
There is no default page (`/`) already... Working paths:
```
127.0.0.1:8000/accounts/<login,logout,etc>
127.0.0.1:8000/home
127.0.0.1:8000/admin
```

I think we should start mark issues.

**Comment by JBetts97** [comment]
Thanks for the super quick response @mateuszz0000 .

I don't know too much about django, but I've also since learnt that you can run the command:
```bash
python3 manage.py superuser
```

Maybe we should create a 'Getting Started' guide?
Thanks again, and as this initial issue has been resolved, I will close this issue :)

Kindest Regards,
Joseph
