### ISSUE TITLE
Can't display homepage (index.html)

### ISSUE THREAD

**Issue by JBetts97** [KalleHallden/BookOmatic#85]
I have created an admin account using the command:   
```
python3 manage.py createsuperuser
```   

However, now when I open the homepage URL I only get this page:
![image](https://user-images.githubusercontent.com/38386086/80971990-71079080-8e15-11ea-852c-f24ad05d21b2.png)

Looking at the source code (index.html in the frontend directory), I can tell that there is supposed to be a page which has the words 'Choose your time slot'. 

![image](https://user-images.githubusercontent.com/38386086/80972198-be83fd80-8e15-11ea-83f3-14f44c09063b.png)

How do I access this page?

Many Thanks for your help.

Kindest Regards,
Joseph

**Comment by RahulKeluskar** [comment]
The index.html has not been associated with any view yet not is it in the templates directory for django to find it and render it. We need to create a static folder to store the js and the css and need to include the html within the templates

**Comment by JBetts97** [comment]
Thanks @RahulKeluskar. 
As my environment is working as expected, I will close this case.
Thanks for your answer.
